sockBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: sockBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: '50'
        lastname:
            type: string
            length: '50'
        email:
            type: string
            length: '100'
            unique: true
        country:
            type: string
            length: '2'
    lifecycleCallbacks: {  }
